# Generated by Django 3.2.8 on 2021-11-02 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medicaldetails',
            old_name='description',
            new_name='detailsDescription',
        ),
    ]
