# Generated by Django 3.2.8 on 2021-11-27 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoMedicalApp', '0003_rename_contact_customer_contact_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companybank',
            old_name='ifsc_no',
            new_name='swift_no',
        ),
        migrations.RenameField(
            model_name='employeebank',
            old_name='ifsc_no',
            new_name='swift_no',
        ),
        migrations.RenameField(
            model_name='medicine',
            old_name='c_gst',
            new_name='gst',
        ),
        migrations.RemoveField(
            model_name='medicine',
            name='s_gst',
        ),
    ]
